### ISSUE TITLE
startServer.sh throws error

### ISSUE THREAD

**Issue by gloyd** [jbrysch/HARP-Initial#8]
module.js:339
    throw err;
    ^

Error: Cannot find module 'properties-reader'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/gloyd/Documents/codebase/JOEY/HARP-Server/HARP-S/server.js:6:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by gloyd** [comment]
@jbrysch can you fix this?

**Comment by jbrysch** [comment]
@gloyd  sudo npm install properties-reader

**Comment by jbrysch** [comment]
@gloyd I have updated the package.json...  All one has to do now is to navigate to the directory which contains the package.json and run "sudo npm install"  it should install all the dependencies...  Once that is complete, then run "npm start"

As for getting mongodb up and running on your Mac, see <a href="https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/">this</a>
